### ISSUE TITLE
Auto collect metadata from the URL

### ISSUE THREAD

**Issue by bumi** [bumi/decent-organizations#11]
We can try to collect some meta data from the URL directly. 
This would give us a bit more data and make it easier for the user to add an entry

- [ ] Image/Logo
- [ ] Description
- [ ] Title
- [ ] ..

**Comment by Plsr** [comment]
Looks like this might come in handy https://github.com/jaimeiniesta/metainspector
We'd need to split the `new` from in two steps then, I guess.
