### ISSUE TITLE
Add CI to repository

### ISSUE THREAD

**Issue by Plsr** [bumi/decent-organizations#25]
Somewhat related to #22. If we have automated deployments from master, it might be good idea to add Travis to the repository to run tests on PRs. Since this is not a private repo, Travis should be free as well. What do you think?

**Comment by bumi** [comment]
yeah! totally. do you want to set it up and add a .travis.yml?

**Comment by Plsr** [comment]
Looks like this can be closed with e50d340ac88047578335f0b9a0285fcb33e4efe9?

**Comment by bumi** [comment]
yeah, sorry.  :D
