### ISSUE TITLE
What are decent organizations?

### ISSUE THREAD

**Issue by myamy** [bumi/decent-organizations#5]
@bumi @Plsr What do you think? 

Very good question. We are trying to figure that out ourselves, and we would love to hear from you if you want to collaborate with us - especially if you disagree.

Some thoughts so far: 

* We humans cannot solve systemic problems - like inequality, unsustainable growth, unfair labor, or climate change - with linear thinking in hierarchical organizations. That's where decent organizations come in.
* Decent organizations put humans first - in why, what and how they operate. 
* Decent organizations are or strive to be decentralized.
* Decent organizations discuss what "decent" means.

**Comment by bumi** [comment]
pretty nice @myamy! I like the idea of having bullet points of thoughts.
I would move the "and we would love to hear from you..." to the end - I'd be worried to loose the reader and like to first give some input and then ask the question.

**Comment by bumi** [comment]
closing this in favor of pull request changing this file content: https://github.com/bumi/decent-organizations/blob/master/app/views/pages/idea.haml
